### ISSUE TITLE
在模型训练的时候报错：forward() missing 1 required positional argument: 'h_band_width'

### ISSUE THREAD

**Issue by xiaodao369** [xiaomingnio/kantts#1]
2023-10-23:10:05:01 ERROR [train_sambert.py:192] forward() missing 1 required positional argument: 'h_band_width'
Traceback (most recent call last):
  File "kantts/bin/train_sambert.py", line 190, in train
    trainer.train()
  File "/home/maas/KAN-TTS/kantts/train/trainer.py", line 199, in train
    self.train_epoch()
  File "/home/maas/KAN-TTS/kantts/train/trainer.py", line 207, in train_epoch
    self.train_step(batch)
  File "/home/maas/KAN-TTS/kantts/train/trainer.py", line 933, in train_step
    fp_label=fp_label,
  File "/root/anaconda3/envs/maas/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/maas/KAN-TTS/kantts/models/sambert/kantts_sambert.py", line 1024, in forward
    return_attns=True,
  File "/root/anaconda3/envs/maas/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/maas/KAN-TTS/kantts/models/sambert/kantts_sambert.py", line 569, in forward
    return_attns=return_attns,
  File "/root/anaconda3/envs/maas/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'h_band_width'
2023-10-23:10:05:01 INFO [train_sambert.py:198] Successfully saved checkpoint @ 2400000steps.

**Comment by LumenForgeX** [comment]
不支持训练哈，本项目只支持推理，训练用原始官方项目 https://github.com/alibaba-damo-academy/KAN-TTS
