### ISSUE TITLE
prepare tts engine failed

### ISSUE THREAD

**Issue by kli017** [xiaomingnio/kantts#6]
生成模型engine成功后运行demo后报错：
```
2023-12-13:05:55:59, INFO [tts.py:85] HifiGAN infer using : trt.......
['input', 'output']
['input']
['output']
2023-12-13:05:56:00, INFO [tts.py:99] Loading HifiGAN checkpoint: ./tensorrt_onnx/model_save/simplify_model_zhizhe_emo.engine
['input', 'memory', 'memory_step', 'pnca_x_attn_mask_step_part1', 'pnca_x_attn_mask_step_part2', 'pnca_h_attn_mask_step', 'pre_x_k', 'pre_x_v', 'x_k_0', 'x_v_0', 'dec_pnca_attn_x_0', 'dec_pnca_attn_h_0', 'x_k_1', 'x_v_1', 'dec_pnca_attn_x_1', 'dec_pnca_attn_h_1', 'x_k_2', 'x_v_2', 'dec_pnca_attn_x_2', 'dec_pnca_attn_h_2', 'x_k_3', 'x_v_3', 'dec_pnca_attn_x_3', 'dec_pnca_attn_h_3', 'x_k_4', 'x_v_4', 'dec_pnca_attn_x_4', 'dec_pnca_attn_h_4', 'x_k_5', 'x_v_5', 'dec_pnca_attn_x_5', 'dec_pnca_attn_h_5', 'x_k_6', 'x_v_6', 'dec_pnca_attn_x_6', 'dec_pnca_attn_h_6', 'x_k_7', 'x_v_7', 'dec_pnca_attn_x_7', 'dec_pnca_attn_h_7', 'x_k_8', 'x_v_8', 'dec_pnca_attn_x_8', 'dec_pnca_attn_h_8', 'x_k_9', 'x_v_9', 'dec_pnca_attn_x_9', 'dec_pnca_attn_h_9', 'x_k_10', 'x_v_10', 'dec_pnca_attn_x_10', 'dec_pnca_attn_h_10', 'x_k_11', 'x_v_11', 'dec_pnca_attn_x_11', 'dec_pnca_attn_h_11', 'output']
['input', 'memory', 'memory_step', 'pnca_x_attn_mask_step_part1', 'pnca_x_attn_mask_step_part2', 'pnca_h_attn_mask_step', 'pre_x_k', 'pre_x_v']
['x_k_1', 'dec_pnca_attn_x_7', 'x_v_10', 'x_k_5', 'dec_pnca_attn_x_3', 'dec_pnca_attn_x_11', 'x_k_11', 'x_k_6', 'dec_pnca_attn_h_4', 'x_k_10', 'dec_pnca_attn_h_0', 'dec_pnca_attn_x_4', 'dec_pnca_attn_x_10', 'x_k_0', 'dec_pnca_attn_h_1', 'dec_pnca_attn_x_6', 'x_v_1', 'dec_pnca_attn_h_2', 'dec_pnca_attn_x_9', 'x_v_8', 'dec_pnca_attn_x_8', 'dec_pnca_attn_x_2', 'x_v_3', 'dec_pnca_attn_h_11', 'output', 'x_k_8', 'x_k_9', 'dec_pnca_attn_h_3', 'x_v_7', 'dec_pnca_attn_h_10', 'dec_pnca_attn_h_9', 'x_k_2', 'x_k_3', 'dec_pnca_attn_h_6', 'dec_pnca_attn_x_5', 'x_v_11', 'dec_pnca_attn_h_8', 'x_v_6', 'x_v_9', 'x_k_4', 'dec_pnca_attn_h_5', 'x_v_0', 'dec_pnca_attn_x_0', 'x_k_7', 'dec_pnca_attn_h_7', 'dec_pnca_attn_x_1', 'x_v_4', 'x_v_2', 'x_v_5']
2023-12-13:05:56:01, INFO [infer_sambert.py:185] Loading sambert engine: ./tensorrt_onnx/model_save/mel_decode_zhizhe_emo.engine
2023-12-13:05:56:03, INFO [infer_sambert.py:192] Loading checkpoint: /home/kai/.cache/modelscope/hub/damo/speech_sambert-hifigan_tts_zh-cn_16k/voices/zhizhe_emo/am/ckpt/checkpoint_0.pth
prepare tts engine failed
lang type empty or not init
not init
general frd process failed...
文本前端推理时间:  0.044345855712890625  ms
Traceback (most recent call last):
  File "demo.py", line 13, in <module>
    outp = sambert_hifigan_tts_man.infer(text="提到个性化定制语音，大家并不陌生", scale=1)
  File "/home/kai/kantts/tts.py", line 227, in infer
    self.concat_process(self.output_dir, os.path.join(self.output_dir, "res_wavs"))
  File "/home/kai/kantts/tts.py", line 118, in concat_process
    wav_concat, sr = sf.read(wav_files[0])
IndexError: list index out of range

```
没定位到是哪里的问题，求助

**Comment by LumenForgeX** [comment]
看着像文本前端出错了，建议看看ttsfrd的输出。        symbols_lst = text_to_mit_symbols1(text, self.fe, self.speaker) https://github.com/xiaomingnio/kantts/blob/744a783036912132c9624fd4e123cd97d1fccd10/tts.py#L138

**Comment by kli017** [comment]
@xiaomingnio 感谢，确实是ttsfrd没初始化，resource.zip默认没解压
